(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var C2=function(a){a.S("cardstatechange",g.XM(a)&&g.YM(a)?1:0)},Mua=function(a){return Math.pow(a,3)},Nua=function(a){return 3*a*a-2*a*a*a},D2=function(a,b){var c=g.xo("use_default_events_client")?void 0:g.hr;
(0,g.y)(b,function(d){d={csn:a,ve:d.getAsJson(),eventType:4};var e={Ok:g.us(a),tk:a};"UNDEFINED_CSN"==a?g.Hs("visualElementShown",d,e):c?g.Tp("visualElementShown",d,c,e):g.ir("visualElementShown",d,e)})},E2=function(a,b){var c=g.xo("use_default_events_client")?void 0:g.hr;
(0,g.y)(b,function(d){var e=void 0,f=(e=void 0===e?!1:e)?16:8;d={csn:a,ve:d.getAsJson(),eventType:f};e={Ok:g.us(a),tk:a,kG:e};"UNDEFINED_CSN"==a?g.Hs("visualElementHidden",d,e):c?g.Tp("visualElementHidden",d,c,e):g.ir("visualElementHidden",d,e)})},H2=function(a){a=g.Pa(a);
delete F2[a];g.Lb(F2)&&G2&&G2.stop()},Pua=function(){G2||(G2=new g.H(function(){Oua()},20));
var a=G2;a.isActive()||a.start()},Oua=function(){var a=(0,g.D)();
g.yb(F2,function(b){Qua(b,a)});
g.Lb(F2)||Pua()},I2=function(a,b,c,d){g.Gn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.A=a;this.I=b;this.duration=c;this.F=d;this.coords=[];this.progress=this.G=0;this.C=null},Qua=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.C);a.C=b;Rua(a,a.progress);1==a.progress?(a.o=0,H2(a),a.zd(),a.Gn()):a.ob()&&a.tv()},Rua=function(a,b){g.Ma(a.F)&&(b=a.F(b));
a.coords=Array(a.A.length);for(var c=0;c<a.A.length;c++)a.coords[c]=(a.I[c]-a.A[c])*b+a.A[c]},Sua=function(a,b){g.Me.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.o},J2=function(a,b,c,d,e){I2.call(this,b,c,d,e);
this.element=a},K2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
J2.call(this,a,b,c,d,e)},L2=function(a){g.A.call(this);
this.u=a||window;this.o=[]},M2=function(a){return a.baseUrl||null},N2=function(a,b){return(0,g.ye)((0,g.Fc)(a,b,void 0),function(c){return!!c})},Tua=function(a,b,c){function d(Ic){var Pb=Ic.hovercardButton;
if(!Pb)return null;Pb=Pb.subscribeButtonRenderer;if(!Pb)return null;var Pe=f(Pb.unsubscribedButtonText),Kn=f(Pb.subscribedButtonText);if(Pb.subscribed){var Ln=f(Pb.subscriberCountWithUnsubscribeText);var Mn=f(Pb.subscriberCountText)}else Ln=f(Pb.subscriberCountText),Mn=f(Pb.subscriberCountWithSubscribeText);var pj=null;return Ic.signinEndpoint&&(pj=g.Gb(Ic,"signinEndpoint","webNavigationEndpointData","url"),!pj)?null:Pe&&(Kn||pj)?{subscribed:Pb.subscribed,subscribeText:Pe,subscribeCount:Ln,unsubscribeText:Kn,
unsubscribeCount:Mn,enabled:Pb.enabled,signinUrl:pj,classic:Ic.useClassicSubscribeButton}:null}
function e(Ic){if(Ic){var Pb=[],Pe=Ic.videoId;Pe&&Pb.push("v="+Pe);(Pe=Ic.playlistId)&&Pb.push("list="+Pe);(Ic=Ic.startTimeSeconds)&&Pb.push("t="+Ic);return"/watch?"+Pb.join("&")}}
function f(Ic){if(!Ic)return null;var Pb=Ic.simpleText;return Pb?Pb:Ic.runs?(0,g.Fc)(Ic.runs,function(Pe){return Pe.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,q=null,r=null,u=null,w=null,z=!1,B=null,E=null,F=null,G=null,O=null;if("VIDEO"==h)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,r=f(b.videoDuration);else if("PLAYLIST"==h)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"==h){if(z=g.Gb(l,"browseEndpoint","browseId"))w=z,m="/channel/"+w;n=!1;q="new";(z=!!b.isSubscribe)?B=d(b):E=f(b.subscribersText)}else"WEBSITE"==
h?((F=g.Gb(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(O=f(b.additionalFeesText)),(n=g.Gb(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g.Gb(b,"title","accessibility","accessibilityData","label");var ma=b.endpoint?b.endpoint.clickTrackingParams:null,Gc="";if(b.metadata){var Wc=f(b.metadata);Wc&&(Gc=Wc)}return{id:"element-"+c,type:h,title:f(b.title),metadata:Gc,callToAction:f(b.callToAction),
Ly:b.image,iconUrl:F,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:r,playlistLength:u,channelId:w,subscribeButton:B,subscribersText:E,isSubscribe:z,targetUrl:m,FH:n,Bc:{itct:ma},qP:q,om:a?a:null,JH:b.isPlaceholder,impressionUrls:N2(b.impressionUrls||[],M2),wH:N2(b.hovercardShowUrls||[],M2),clickUrls:N2(l.loggingUrls||[],M2),visualElement:g.ms(b.trackingParams),productPrice:G,
additionalFeesText:O}},O2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=N2(a.impressionUrls||[],M2);a.trackingParams&&(c.visualElement=g.ms(a.trackingParams));c.elements=N2(a.elements||[],function(d,e){return Tua(b,d,e)});
return c},P2=function(a){g.uN.call(this,a);
this.B=this.u=null;this.o={};this.G={};this.F=this.A=null;this.M=[];a=a.O();this.N=g.sy(a)||g.uy(a);this.R=!0;this.I=0;this.C=new g.Xr(this);g.C(this,this.C);this.C.L(this.player,g.bz("creatorendscreen"),this.qI);this.C.L(this.player,"crx_creatorendscreen",this.rI);this.C.L(this.player,"resize",this.JA);this.C.L(window,"focus",this.lO);this.load();var b=g.se("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Je(this,function(){g.xe(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Uua=function(a){return a.player.getVideoData().dc?"current":a.N?"new":"current"},Q2=function(a){return"creator-endscreen-editor"===a.player.O().playerStyle},R2=function(a,b,c){c=void 0===c?!0:c;
g.XP(a.player.app,"creatorendscreen",void 0);a.A&&(a.A.dispose(),a.A=null,a.F.dispose(),a.F=null);for(var d in a.o)a.o[d].dispose();a.o={};a.G={};0<a.M.length&&(a.M.forEach(function(l){l.dispose()}),a.M.length=0);
a.I=0;if((a.u=b)&&b.elements){c&&Vua(a);c=[];d=new g.Zy(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.O().o||(a.A=new g.U({D:"div",J:"ytp-ce-shadow"}),g.gN(a.player,a.A.element,4),a.F=new g.PN(a.A,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=Wua(a,e);a.o[e.id]=f;a.G[e.id]=e;g.gN(a.player,f.element,4);var h=new g.Zy(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Xua(a,f,e)}g.cN(a.player,c);
a.JA()}},Vua=function(a){var b=g.qs(),c=g.ts();
c&&b&&a.u.visualElement&&g.Ns(c,b,a.u.visualElement)},Wua=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",Y:["ytp-ce-element","ytp-ce-video"],P:{tabindex:"0","aria-label":b.om||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-covering-image",P:S2(b)},{D:"div",J:"ytp-ce-covering-shadow-top"},{D:"a",J:"ytp-ce-covering-overlay",P:{href:T2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",Y:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Pn(b.title||"")},W:b.title},{D:"div",J:"ytp-ce-video-duration",W:b.videoDuration}]}]};
c=new g.U(c);break;case "PLAYLIST":c={D:"div",Y:["ytp-ce-element","ytp-ce-playlist"],P:{tabindex:"0","aria-label":b.om||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-covering-image",P:S2(b)},{D:"div",J:"ytp-ce-covering-shadow-top"},{D:"a",J:"ytp-ce-covering-overlay",P:{href:T2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",Y:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Pn(b.title||"")},W:b.title},{D:"div",J:"ytp-ce-playlist-count",K:[{D:"div",
J:"ytp-ce-playlist-icon"},{D:"div",J:"ytp-ce-playlist-count-text",W:b.playlistLength}]}]}]};c=new g.U(c);break;case "CHANNEL":c={D:"div",Y:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],P:{tabindex:"0","aria-label":b.om||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",K:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",
K:[{D:"div",J:"ytp-ce-expanding-overlay-body",K:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{D:"a",Y:["ytp-ce-channel-title","ytp-ce-link"],P:{href:T2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Pn(b.title||"")},W:b.title},b.subscribeButton?{D:"div",J:"ytp-ce-subscribe-container",K:[{D:"div",J:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",J:"ytp-ce-channel-subscribers-text",W:b.subscribersText}:"",b.metadata?{D:"div",Y:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
W:b.metadata}:""]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",P:S2(b)}]};c=new g.U(c);var d=g.ee(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.I(d,"ytp-ce-subscribe-button");if(a.player.O().o){var e=null;var f=b.Bc.itct}else e="endscreen",f=null;e=new g.XO(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.M.push(e)}break;case "WEBSITE":c={D:"div",Y:["ytp-ce-element","ytp-ce-website"],P:{tabindex:"0","aria-label":b.om||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",K:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",K:[{D:"div",J:"ytp-ce-expanding-overlay-body",
K:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",J:"ytp-ce-website-title",P:{dir:g.Pn(b.title||"")},W:b.title},{D:"div",J:"ytp-ce-website-metadata",W:b.metadata},{D:"a",Y:["ytp-ce-website-goto","ytp-ce-link"],P:{href:T2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",P:S2(b)},{D:"div",J:"ytp-ce-expanding-icon",P:Yua(b.iconUrl)}]};c=new g.U(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",J:"ytp-ce-merchandise-price-container",
K:[{D:"div",J:"ytp-ce-merchandise-price",W:b.productPrice}]},b.additionalFeesText&&c.K.push({D:"div",J:"ytp-ce-merchandise-additional-fees",W:b.additionalFeesText})),c={D:"div",Y:["ytp-ce-element","ytp-ce-merchandise"],P:{tabindex:"0","aria-label":b.om||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",K:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",K:[{D:"div",
J:"ytp-ce-expanding-overlay-body",K:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",J:"ytp-ce-merchandise-title",P:{dir:g.Pn(b.title||"")},W:b.title},c,{D:"div",J:"ytp-ce-merchandise-metadata",W:b.metadata},{D:"a",Y:["ytp-ce-merchandise-goto","ytp-ce-link"],P:{href:T2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",P:S2(b)},{D:"div",J:"ytp-ce-merchandise-invideo-cta-container",K:[{D:"div",J:"ytp-ce-merchandise-invideo-cta",
W:b.callToAction}]}]},c=new g.U(c)}b.JH&&g.I(c.element,"ytp-ce-placeholder");return c},S2=function(a){if(a.Ly)var b=a.Ly.thumbnails;
return Yua(b?b[b.length-1].url:null)},Yua=function(a){return a?{style:"background-image: url("+a+")"}:{}},Xua=function(a,b,c){function d(){h(1)}
function e(){h(-1)}
b.na("mouseenter",(0,g.x)(a.Qu,a,b,c));b.na("mouseleave",(0,g.x)(a.zv,a,b,c));a.player.O().o||b.na("click",(0,g.x)(function(l){g.I(l.element,"ytp-ce-element-hover")},a,b));
b.na("click",(0,g.x)(a.VB,a,c));b.na("keypress",(0,g.x)(a.VB,a,c));b.na("focus",(0,g.x)(function(l,m){this.Qu(l,m)},a,b,c));
b.na("blur",(0,g.x)(function(l,m){this.zv(l,m)},a,b,c));
b.na("touchstart",(0,g.x)(a.Qu,a,b,c));var f=g.ge("ytp-ce-expanding-overlay-hider",b.element);f&&b.L(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.En(b.element,"ytp-ce-element-hover");g.En(b.element,"ytp-ce-force-expand")});
b.na("keydown",(0,g.x)(function(l,m){this.R=9==m.keyCode&&!m.shiftKey},a,b));
var h=(0,g.x)(function(l,m,n){this.I+=n;0<this.I?(g.I(l.element,"ytp-ce-force-expand"),U2(this,m.id,!0)):(g.En(l.element,"ytp-ce-force-expand"),g.En(l.element,"ytp-ce-element-hover"),U2(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.na("blur",g.Qa(function(){"none"!=m.style.display&&a.R&&m.focus()})),l.L(m,"focus",d),l.L(m,"blur",e))},a,b);
c(g.ge("ytp-sb-subscribe",b.element));c(g.ge("ytp-sb-unsubscribe",b.element));b.na("focus",d);b.na("blur",e)},T2=function(a,b){var c=a.player.O();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.Xy(c)+b}else return"";return b},U2=function(a,b,c){a.A&&(c?a.F.show():a.F.hide());
for(var d in a.o)d!=b&&g.J(a.o[d].element,"ytp-ce-element-shadow-show",c)},V2=function(a,b,c){function d(){f||(e++,e==b.length&&(h.stop(),c&&c()))}
if(!b||0==b.length||Q2(a))c&&c();else{b=Zua(a,b);var e=0,f=!1,h=new g.H(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.tr(b[a],d)}},W2=function(a,b,c){V2(a,b.clickUrls,c);
(a=g.ts())&&b.FH&&g.Os(a,b.visualElement)},Zua=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push($ua(b[e],c));return d},$ua=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},ava=function(a){return Array.isArray(a)&&a.length?a[0]:a},X2=function(a){return"string"===typeof a?a:""},Y2=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},cva=function(a){var b=bva;
if(null==a)return null;if(g.La(a)){var c=[];(0,g.y)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},dva=function(a){this.externalId=a},eva=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},Z2=function(a){if(!a)return null;
var b=g.zc(X2(a.value));b=g.wc(b);if(!b)return null;var c=Y2(a.target,fva,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new eva(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},$2=function(a){return a.value?a.value:null},gva=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},bva=function(a){if(!a)return null;
var b=Y2(a.type,hva),c=Y2(a.trigger,iva),d=ava(a.url);d=Z2(d?d:null);a=ava(a.subscribeData);var e=a?a:null;e?(a=X2(e.external_user_id),e=X2(e.subscription_token),a=a&&e?new dva(a):null):a=null;return b?new gva(b,c,d,a):null},a3=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},jva=function(a,b){return g.ab(a.o,b,void 0)},kva=function(a,b){this.merchant=a;
this.price=b},lva=function(a){this.o=a},mva=function(a,b,c){b&&(c?b3(a,(0,g.Fc)(b,g.Qa(function(d,e){return g.en(e,d)},c))):b3(a,b))},b3=function(a,b,c,d){var e=1,f=-1;
if(c){var h=!1;var l=function(){e--;e||h||(clearTimeout(f),h=!0,c())};
f=setTimeout(function(){h=!0;c()},1E3)}(0,g.y)(b||[],function(m){e++;
g.tr(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},nva=function(a,b,c,d,e,f,h){this.o=a;
this.A=b;this.B=c;this.videoData=d;this.logger=e;this.H=f;this.u=h},ova=function(a){this.o=a},d3=function(a){return a.customMessage?c3("div","iv-card-message",a.customMessage):""},e3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",J:"iv-card-image",P:{style:c},K:d}},f3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.y)(b.metaInfo,function(d){c.push(c3("li","",d))},a);
return{D:"ul",J:"iv-card-meta-info",K:c}},c3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Pn(c);return{D:a,P:b,W:c}},pva=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Po&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Po+");");c.dir=g.Pn(a.customMessage);var d=[{D:"span",W:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",J:"iv-card-link-icon"}));return{D:"div",Y:b,P:c,K:d}},g3=function(a,b,c,d){d&&(0,g.y)(b,function(e){this.o(e,d,c.id,c.Bc,c.Wd.click,5)},a)},qva=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},rva=function(a,b){return b?b:qva(a)?"current":"new"},h3=function(a,b){g.A.call(this);
var c=this;this.Pa=a;this.context=b;this.Ww=!1;this.sa=new Map;this.oa=new Map;this.context.H.addEventListener(g.bz("annotations_module"),function(d){(d=c.sa.get(d))&&d.apply(c)});
this.context.H.addEventListener("crx_annotations_module",function(d){(d=c.oa.get(d))&&d.apply(c)})},sva=function(a,b,c,d,e){var f=$2(b);
if(f){var h=rva(f,b.target),l=(0,g.x)(function(){b.o&&this.context.H.pauseVideo();var m=this.context.videoData.dc||!1,n=g.$p(f||"");m&&n&&(n.v||n.list)?g.XT(this.context.H.app,n.v,c,n.list,!1,void 0):g.WN(f||"","current"==h?"_top":void 0,c)},a);
"new"==h&&(l(),l=null);b3(a.context.logger,d,l,e);qva(f)||(a=g.ts(),d=c.itct,a&&d&&g.Os(a,g.ms(d)))}},tva=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},i3=function(a,b,c){return{Tz:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
ND:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
Rr:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},l3=function(a,b,c){h3.call(this,b,c);
var d=this;this.u=a;this.fa=this.Ia=this.C=this.Ea=!1;this.ga=null;this.aa=new g.H(g.Ia,c.B.yb?4E3:3E3);g.C(this,this.aa);this.za=new g.H(g.Ia);g.C(this,this.za);this.Z=new ova((0,g.x)(this.Sl,this),(0,g.x)(this.hq,this));this.U=new g.U({D:"div",J:"iv-drawer",P:{id:"iv-drawer"},K:[{D:"div",J:"iv-drawer-header",P:{"aria-role":"heading"},K:[{D:"span",J:"iv-drawer-header-text"},{D:"button",Y:["iv-drawer-close-button","ytp-button"],P:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",J:"iv-drawer-content"}]});
g.C(this,this.U);this.F=this.U.element;this.ua=new g.PN(this.U,330);g.C(this,this.ua);this.Da=g.ge("iv-drawer-header-text",this.F);this.B=g.ge("iv-drawer-content",this.F);this.A=[];this.Ba=this.R=this.G=this.ea=this.o=null;this.T=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Ia&&j3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ia=d.C)&&k3(d)});
this.N=this.I=this.ba=null;this.M=0},uva=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){j3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){k3(a)});
var c=b.data.headerText;g.Be(a.Da,c);a.R&&a.R.setAttribute("title",c);a.ba=g.ms(b.data.trackingParams);a.N=g.ms(b.data.closeTrackingParams);a.I=g.ms(b.data.iconTrackingParams)},vva=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.M;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.M,type:"simple",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Bc:m3(a,c,b,d),sponsored:!1,Wd:i3(d,e,d.command),bh:d.trackingParams?g.ms(d.trackingParams):null,nf:e.trackingParams?
g.ms(e.trackingParams):null,le:f&&f.trackingParams?g.ms(f.trackingParams):null,imageUrl:n3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.S(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Po:null,title:d.title?g.S(d.title):"",customMessage:d.callToAction?g.S(d.callToAction):"",url:d.command.urlEndpoint.url?Z2({pause_on_navigation:!a.context.videoData.xa,target:"new",value:d.command.urlEndpoint.url}):null};o3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.M,type:"collaborator",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Bc:m3(a,c,b,d),sponsored:!1,Wd:i3(d,e,d.endpoint),bh:d.trackingParams?g.ms(d.trackingParams):null,nf:e.trackingParams?g.ms(e.trackingParams):null,le:f&&f.trackingParams?
g.ms(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.S(d.customText):null,SC:n3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.S(d.channelName):"",metaInfo:[d.subscriberCountText?g.S(d.subscriberCountText):""],url:Z2({pause_on_navigation:!a.context.videoData.xa,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};o3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.M,type:"playlist",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Bc:m3(a,c,b,d),sponsored:!1,Wd:i3(d,e,d.action),bh:d.trackingParams?g.ms(d.trackingParams):null,nf:e.trackingParams?g.ms(e.trackingParams):null,le:f&&f.trackingParams?g.ms(f.trackingParams):
null,ko:n3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.S(d.customMessage):null,playlistVideoCount:g.S(d.playlistVideoCount),title:d.playlistTitle?g.S(d.playlistTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.videoCountText?g.S(d.videoCountText):""],url:Z2({pause_on_navigation:!a.context.videoData.xa,target:"new",value:tva(d.action)})};o3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.M,type:"video",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Bc:m3(a,c,b,d),sponsored:!1,Wd:i3(d,e,d.action),bh:d.trackingParams?g.ms(d.trackingParams):null,nf:e.trackingParams?g.ms(e.trackingParams):null,le:f&&f.trackingParams?g.ms(f.trackingParams):null,ko:n3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.S(d.lengthString):null,customMessage:d.customMessage?g.S(d.customMessage):null,title:d.videoTitle?g.S(d.videoTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.viewCountText?g.S(d.viewCountText):""],isLiveNow:!!d.badge,url:Z2({pause_on_navigation:!a.context.videoData.xa,target:"new",value:tva(d.action)})};o3(a,c)}a.M++},n3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height==b||290==a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},m3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},xva=function(a,b){var c=wva(a,b);
c&&(c==a.o&&(a.o=null),a.u.removeCueRange(c.card.id),g.xe(c.Ys),g.ib(a.A,c),a.So(),p3(a))},j3=function(a,b,c){if(!a.C){a.ua.show();
a.ea=new g.H(function(){g.I(a.context.H.getRootNode(),g.KL.IV_DRAWER_OPEN)},0);
a.ea.start();a.ga=g.dp(a.B,"mousewheel",(0,g.x)(a.vM,a));a.C=!0;var d=g.ts();d&&a.ba&&a.N&&D2(d,[a.ba,a.N]);var e={TRIGGER_TYPE:b};(0,g.y)(a.A,function(f){f.sA||(f.sA=!0,mva(a.context.logger,f.card.Wd.Tz,e));d&&D2(d,[f.card.bh])});
C2(a.u);c&&(a.G=new g.H(function(){a.ya=a.R;a.Ba.focus()},330),a.G.start())}},k3=function(a){a.C&&(a.ua.hide(),g.ep(a.ga),a.ga=null,g.En(a.context.H.getRootNode(),g.KL.IV_DRAWER_OPEN),a.C=!1,C2(a.u),a.G&&a.G.stop(),a.G=new g.H(function(){a.ya&&(a.ya.focus(),a.ya=null)},330),a.G.start())},yva=function(a){var b=g.ge("iv-drawer-close-button",a.F);
a.context.o.na(b,"click",a.SF,a);a.context.o.na(a.B,"touchend",function(){a.aa.start()});
a.context.o.na(a.B,"scroll",a.fG,a);a.context.u.subscribe("onHideControls",function(){a.fa=!0});
a.context.u.subscribe("onShowControls",function(){a.fa=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.fa=g.Cn(a.u.getRootNode(),"ytp-autohide")});
a.T.push(g.Oo("iv-button-shown",a.OH,a));a.T.push(g.Oo("iv-button-hidden",a.NH,a));a.T.push(g.Oo("iv-teaser-shown",a.RH,a));a.T.push(g.Oo("iv-teaser-hidden",a.QH,a));a.T.push(g.Oo("iv-teaser-clicked",a.PH,a))},o3=function(a,b){a.Ea||(g.Dn(a.wa(),[g.KL.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]),g.gN(a.u,a.F,5),yva(a),a.R=g.ge("ytp-cards-button",a.u.getRootNode()),a.Ba=g.ge("iv-drawer-close-button",a.F),a.Ea=!0);xva(a,b.id);var c=zva(a,b);if(c){var d={card:b,Ys:c.element,sA:!1},e=Ava(a,d);g.pb(a.A,e,0,d);c.ca(a.B,e);a.So();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Qa(a.aP,d)):(c=1E3*a.context.H.getCurrentTime(),5E3>c&&c>b.startMs&&a.AD(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Qa(a.AD,d)),p3(a))}},zva=function(a,b){switch(b.type){case "simple":var c=
a.Z;
var d=b.displayDomain?{D:"div",J:"iv-card-image-text",W:b.displayDomain}:"";var e=pva(b);d={D:"div",Y:["iv-card"],K:[{D:"a",J:"iv-click-target",P:{href:$2(b.url)},K:[e3(b.imageUrl,d),{D:"div",J:"iv-card-content",K:[c3("h2",void 0,b.title),e]}]}]};d=new g.U(d);g3(c,g.fe("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.Z,d={D:"div",Y:["iv-card","iv-card-channel"],K:[{D:"a",Y:["iv-click-target"],P:{href:$2(b.url),"data-ytid":b.channelId},K:[e3(b.SC),{D:"div",J:"iv-card-content",
K:[d3(b),{D:"h2",J:"iv-card-primary-link",W:b.title},f3(c,b)]}]}]},d=new g.U(d),g3(c,g.fe("iv-click-target",d.element),b,b.url),d;case "playlist":return c=a.Z,d={D:"div",Y:["iv-card","iv-card-playlist"],K:[{D:"a",J:"iv-click-target",P:{href:$2(b.url)},K:[e3(b.ko,{D:"div",J:"iv-card-image-overlay",K:[{D:"span",J:"iv-card-playlist-video-count",W:b.playlistVideoCount}]}),{D:"div",J:"iv-card-content",K:[d3(b),c3("h2","iv-card-primary-link",b.title),f3(c,b)]}]}]},d=new g.U(d),g3(c,g.fe("iv-click-target",
d.element),b,b.url),d;case "productListing":c=a.Z;var f=!g.eb(b.offers);d=["iv-card"];e="";var h=pva(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],h=[],f.price&&h.push({D:"div",J:"iv-card-offer-price",W:f.price}),f.merchant&&h.push({D:"div",J:"iv-card-offer-merchant",W:f.merchant}),h={D:"div",K:h});d={D:"div",Y:d,P:{tabindex:"0"},K:[{D:"a",Y:["iv-card-image","iv-click-target"],P:{style:"background-image: url("+b.imageUrl+");",href:$2(b.url),"aria-hidden":"true",tabindex:"-1"}},
{D:"div",J:"iv-card-content",K:[b.sponsored?{D:"div",J:"iv-card-sponsored",K:["Sponsored",{D:"div",J:"iv-ad-info-container",K:[{D:"div",J:"iv-ad-info",W:"{{adInfo}}"},{D:"div",J:"iv-ad-info-icon-container",K:[{D:"div",J:"iv-ad-info-icon"},{D:"div",J:"iv-ad-info-callout"}]}]}]}:"",{D:"a",J:"iv-click-target",P:{href:$2(b.url)},K:[c3("h2",e,b.title),h]}]}]};d=new g.U(d);e=g.se("span");g.Be(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.Cb(e,"adInfo");g3(c,g.fe("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.Z,d=b.isLiveNow?{D:"span",Y:["yt-badge","yt-badge-live"],W:"LIVE NOW"}:"",d={D:"div",Y:["iv-card","iv-card-video"],K:[{D:"a",J:"iv-click-target",P:{href:$2(b.url)},K:[e3(b.ko,b.videoDuration?{D:"span",J:"iv-card-video-duration",W:b.videoDuration}:""),{D:"div",J:"iv-card-content",K:[d3(b),c3("h2","iv-card-primary-link",b.title),f3(c,b),d]}]}]},d=new g.U(d),g3(c,g.fe("iv-click-target",d.element),b,b.url),
d}return null},Ava=function(a,b){if(0==a.A.length)return 0;
var c=g.bb(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},Bva=function(a){return a.o?"productListing"==a.o.card.type:(0,g.ui)(a.A,function(b){return"productListing"==b.card.type})},p3=function(a){g.J(a.u.getRootNode(),"ytp-cards-shopping-active",Bva(a))},Cva=function(a,b){if(a.U.La()){var c=new I2([0,
a.B.scrollTop],[0,b.Ys.offsetTop],600,Nua);a.context.A.na(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.A.na(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.JL(a.U,!0),a.B.scrollTop=b.Ys.offsetTop,g.JL(a.U,!1)},q3=function(a){return a.o&&a.o.card?a.o.card:a.A[0]&&a.A[0].card?a.A[0].card:null},wva=function(a,b){return g.ab(a.A,function(c){return c.card.id==b})},r3=function(a,b,c){h3.call(this,a,b);
this.annotation=c;this.isActive=!1},Dva=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},s3=function(a,b,c){r3.call(this,a,b,c);
this.u=null;this.G=!1;this.A=null;this.B=!1;this.o=this.F=this.C=null},t3=function(a,b,c){r3.call(this,a,b,c);
this.M=this.C=this.N=!1;this.G=5E3;this.B=null;this.I=g.re("DIV","iv-promo-contents");this.u=this.A=this.o=null;this.F=new g.H(function(){this.o.setAttribute("aria-hidden",!0);g.Ph(this.A,!1);g.Ph(this.u,!0)},700,this);
g.C(this,this.F)},Eva=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.wa().setAttribute("aria-hidden",!0);a.wa().setAttribute("aria-label","Promotion");a.wa().tabIndex=0;var e=a.annotation.Fc(),f=b.image_url;if(f){var h=g.re("DIV",["iv-promo-img","iv-click-target"]);f=g.re("IMG",{src:f,"aria-hidden":"true"});h.appendChild(f);b.video_duration&&!b.is_live?(f=g.re("SPAN","iv-promo-video-duration",
b.video_duration),h.appendChild(f)):b.playlist_length&&(f=g.re("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),h.appendChild(f));e&&a.Sl(h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.re("A","iv-promo-txt"),g.bd(f,$2(e)),a.o=f):a.o=g.re("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.re("P",null,g.re("STRONG",null,b.text_line_1));var m=g.re("P",null,g.re("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
var n=g.re("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.re("BUTTON",["iv-button","iv-promo-button"],g.re("SPAN","iv-button-content",f));var q=g.re("DIV","iv-promo-button-container");q.appendChild(f);e&&a.Sl(a.wa(),e,a.annotation.id,b.session_data,void 0,c)}g.I(a.o,"iv-click-target");e&&a.Sl(a.o,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.re("P",null,g.re("SPAN",null,b.text_line_1)),m=g.re("P",null,g.re("STRONG",null,b.text_line_2)),b.is_live&&(l=
m,m=g.re("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.I(a.o,"iv-click-target"),e&&a.Sl(a.o,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.I.appendChild(a.o);q&&a.I.appendChild(q);c=g.re("DIV","iv-promo-actions");a.u=g.re("BUTTON",["iv-promo-expand","ytp-button"]);a.u.title="Expand";a.context.o.na(a.u,"click",g.Qa(a.iu,5E3),a);c.appendChild(a.u);g.Ph(a.u,!1);a.context.o.na(a.wa(),"mouseover",a.ZG,a);a.context.o.na(a.wa(),
"mouseout",a.YG,a);a.context.o.na(a.wa(),"touchend",g.Qa(a.iu,5E3),a);a.A=g.re("BUTTON",["iv-promo-close","ytp-button"]);a.A.title="Close";a.context.o.na(a.A,"click","cta"==a.annotation.style&&b.text_line_3?a.SG:a.QG,a);c.appendChild(a.A);g.Dn(a.wa(),d);h&&(a.wa().appendChild(h),n&&h.appendChild(n));a.wa().appendChild(a.I);a.wa().appendChild(c)},Fva=function(a){a.C||a.M||a.B||(g.I(a.wa(),"iv-promo-collapsed"),a.C=!0,a.F.start())},Gva=function(a){a.F.stop();
a.C&&(g.Fn(a.wa(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.Ph(a.u,!1),g.Ph(a.A,!0))},Hva=function(a,b){a.B||(a.B=g.Xf(function(){u3(this);
Fva(this)},b,a))},u3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},v3=function(a){g.uN.call(this,a);
this.N=!1;this.M=0;this.G={};this.Z=new lva(a);this.C=new g.Xr(this);g.C(this,this.C);this.F=this.A=null;this.C.L(this.player,"onVideoAreaChange",(0,g.x)(this.S,this,"onVideoAreaChange"));this.C.L(this.player,"onHideControls",(0,g.x)(this.S,this,"onHideControls"));this.C.L(this.player,"onShowControls",(0,g.x)(this.S,this,"onShowControls"));this.C.L(this.player,"resize",(0,g.x)(this.S,this,"resize"));this.C.L(this.player,"presentingplayerstatechange",(0,g.x)(this.S,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.oI,this);this.subscribe("resize",this.gr,this);this.player.O().M.subscribe("vast_info_card_add",this.DC,this);this.T=new g.Xr(this);g.C(this,this.T);this.U=g.re("DIV","video-custom-annotations");this.u=new g.U({D:"div",Y:["ytp-player-content","ytp-iv-player-content"]});g.C(this,this.u);g.gN(this.player,this.u.element,4);this.u.hide();this.B=new g.U({D:"div",Y:["ytp-iv-video-content"]});g.C(this,this.B);g.ue(this.B.element,g.re("DIV","video-annotations",
this.U));this.I=this.o=null;this.R=[];Iva(this)&&this.load();var b=g.se("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Je(this,function(){g.xe(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Jva=function(){var a=g.re("DIV",["annotation",
"annotation-type-custom"]);g.Ph(a,!1);return a},Kva=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},Iva=function(a){var b=a.player.O();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.vE||b.M.get(a.videoId)||g.NB(a)||g.OB(a)?!0:!1},Lva=function(a,b){var c=!b.isCued()&&!g.T(b,1024);
g.JL(a.u,c);g.JL(a.B,c)},Mva=function(a,b,c){a.N=!0;
a.F=g.rq(b,c)},Nva=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Na(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Nva(a,e))}return c},Ova=function(a,b,c){return!(a.loaded&&a.M==b&&a.player.getVideoData().videoId==
c)},Rva=function(a){var b=a.player.getVideoData();
if(b.We){var c=a.player.O().M.get(b.videoId);if(c){var d={format:"XML",Te:{},method:"POST",withCredentials:!0};d.zd=(0,g.x)(function(e,f,h){Ova(this,e,f)||(e=g.lq(h)&&h.responseXML?h.responseXML:null)&&w3(this,e)},a,a.M,b.videoId);
g.tp()&&(d.zd=Pva(a,d.zd));d.Eb={ic_only:"1"};Qva(d,c);a.N=!0;g.rq(b.We,d)}}},Qva=function(a,b){a.method="POST";
a.Eb=a.Eb||{};b.Xo&&(a.Eb.ic_coll=b.Xo);b.Yo&&(a.Eb.ic_xml=b.Yo);b.oo&&(a.Eb.ic_track=b.oo)},Sva=function(a){var b=new g.U({D:"div"});
g.Ph(b.element,!1);var c=new l3(a.player,b.element,x3(a));g.C(c,b);b.ca(a.u.element);c.Yn();return c},x3=function(a){if(!a.I){var b=new L2(a);
g.C(a,b);var c=new g.B1(a);g.C(a,c);a.I=new nva(b,c,a.player.O(),a.player.getVideoData(),a.Z,a.player,a.Wi)}return a.I},w3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.ts();if(e){var f=g.qs();f&&g.Is(g.xo("use_default_events_client")?void 0:g.hr,e,f,[g.ms(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var h=Nva(a,d[e]);f=null;try{if(h){var l=h.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=Y2(h.type,Tva),r=Y2(h.style,Uva),u=X2(h.data),w=0!=u.length?JSON.parse(u):{},z=cva(h.action);f=n&&q?new a3(n,q,r,z,w):null}else f=null}catch(O){}if(f){a:{switch(f.type){case "branding":case "promotion":h=
!0;break a}h=!1}if(h){h=a;m=f;var B=Jva(),E=null;switch(m.type){case "branding":if(h.player.O().Pa)break;h.u.element.appendChild(B);E=new s3(B,x3(h),m);break;case "promotion":g.gN(h.player,B,4),E=new t3(B,x3(h),m)}E&&E.Yn();if(h=E)g.C(a,h),a.G[f.id]=h}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=Sva(a),g.C(a,a.o));if("card"==f.type){if(c=a.o,E=f&&f.data&&f.data.card_type)switch(h=f.data.tracking||{},h={Tz:h.impression,click:h.click,close:h.close,ND:h.teaser_impression,Rr:h.teaser_click},m=
f.data.tracking_params||{},B=null,E){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Bc:f.data.session_data||{},sponsored:f.data.sponsored||!1,Wd:h,bh:m.card?g.ms(m.card):null,nf:m.teaser?g.ms(m.teaser):null,le:m.icon?g.ms(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,SC:f.data.image_url,
title:f.data.title,metaInfo:f.data.meta_info,url:Z2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};o3(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Bc:f.data.session_data||{},sponsored:f.data.sponsored||!1,Wd:h,bh:m.card?g.ms(m.card):null,nf:m.teaser?g.ms(m.teaser):null,le:m.icon?
g.ms(m.icon):null,ko:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:Z2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};o3(c,f);break;case "productListing":f.data.signin_url&&(B=Z2({target:"current",value:f.data.signin_url}));E=[];for(var F=f.data.offers||[],G=0;G<F.length;G++)E.push(new kva(g.jd(F[G].merchant),g.jd(F[G].price)));
f={oU:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Bc:f.data.session_data||{},sponsored:f.data.sponsored||!1,Wd:h,bh:m.card?g.ms(m.card):null,nf:m.teaser?g.ms(m.teaser):null,le:m.icon?g.ms(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,Po:f.data.button_icon_url?f.data.button_icon_url:
null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:Z2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),NU:B,MU:f.data.signin_title?f.data.signin_title:null,LU:f.data.signin_message?f.data.signin_message:null,offers:E};o3(c,f);break;case "simple":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||
!1,Bc:f.data.session_data||{},sponsored:f.data.sponsored||!1,Wd:h,bh:m.card?g.ms(m.card):null,nf:m.teaser?g.ms(m.teaser):null,le:m.icon?g.ms(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,Po:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:Z2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};
o3(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Bc:f.data.session_data||{},sponsored:f.data.sponsored||!1,Wd:h,bh:m.card?g.ms(m.card):null,nf:m.teaser?g.ms(m.teaser):null,le:m.icon?g.ms(m.icon):null,ko:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,
metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:Z2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},o3(c,f)}}else uva(a.o,f);c=!0}}}c&&(C2(a.player),a.gr())},Vva=function(a,b){var c=!1;
a.o||(a.o=Sva(a),g.C(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())vva(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.S(b.headerText):"",g.Be(c.Da,d),c.R&&c.R.setAttribute("title",d),c.ba=b.trackingParams?g.ms(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.ms(b.closeButton.infoCardIconRenderer.trackingParams):null,c.I=b.icon.infoCardIconRenderer.trackingParams?g.ms(b.icon.infoCardIconRenderer.trackingParams):null,C2(a.player),a.gr())},
Wva=function(a,b,c,d,e){if(!a.player.O().Pa){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new gva("openUrl","click",new eva("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.S(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.S(b.subscriberCountText))):(b.subscriberCountText&&(e=g.S(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.S(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.S(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.S(b.subscribedButtonText),unsubscribeCount:h,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new a3(c,"branding","branding",f,d);d=Jva();a.u.element.appendChild(d);f=new s3(d,x3(a),f);f.Yn();g.C(f,f);a.G[c]=f}},Pva=function(a,b){return(0,g.x)(function(){if(!this.ha()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Qa.apply(window,c);this.R.push(g.rp(b))}},a)},F2={},G2=null;g.Sa(I2,g.Gn);g.k=I2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.A;else if(this.ob())return!1;H2(this);this.startTime=a=(0,g.D)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.dr();this.Xe("play");-1==this.o&&this.Xe("resume");this.o=1;var b=g.Pa(this);b in F2||(F2[b]=this);Pua();Qua(this,a);return!0};
g.k.stop=function(a){H2(this);this.o=0;a&&(this.progress=1);Rua(this,this.progress);this.Xe("stop");this.Gn()};
g.k.pause=function(){this.ob()&&(H2(this),this.o=-1,this.Xe("pause"))};
g.k.X=function(){0==this.o||this.stop(!1);this.Xe("destroy");I2.uc.X.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.tv=function(){this.Xe("animate")};
g.k.Xe=function(a){this.dispatchEvent(new Sua(a,this))};
g.Sa(Sua,g.Me);g.Sa(J2,I2);J2.prototype.B=g.Ia;J2.prototype.tv=function(){this.B();J2.uc.tv.call(this)};
J2.prototype.Gn=function(){this.B();J2.uc.Gn.call(this)};
J2.prototype.dr=function(){this.B();J2.uc.dr.call(this)};
g.Sa(K2,J2);K2.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.t(L2,g.A);L2.prototype.na=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.dp(a,b,c);this.o.push(a);return a};
L2.prototype.Iu=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.mp(a,b,c);this.o.push(a);return a};
L2.prototype.nb=function(a){g.ep(a);g.ib(this.o,a)};
L2.prototype.X=function(){g.ep(this.o);this.o.length=0;g.A.prototype.X.call(this)};g.t(P2,g.uN);g.k=P2.prototype;g.k.load=function(){g.uN.prototype.load.call(this);if(!Q2(this)){var a=g.MB(this.player.getVideoData());if(a)a=O2(a,Uua(this)),R2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.B&&this.B.abort();a={method:"POST",zd:(0,g.x)(this.KL,this,a),Te:{v:a},withCredentials:!0};this.N&&(a.Te.ptype="embedded");var c=this.player.getVideoData().mp;c&&(a.Eb={ad_tracking:c});if(b=g.LB(b))if(b=g.zc(b),b=g.wc(b))this.B=g.rq(b,a)}}};
g.k.unload=function(){R2(this,null);this.B&&(this.B.abort(),this.B=null);g.uN.prototype.unload.call(this)};
g.k.gd=function(a,b){if(!Q2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=O2(b,"new");R2(this,c);return!0}return null};
g.k.getOptions=function(){return Q2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.KL=function(a,b){var c=this.B=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=O2(c,Uua(this)))}R2(this,c)};
g.k.JA=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Xva.length;f++){var h=Math.abs(b.width-Xva[f]);if(-1==e||d>=h)e=f,d=h}d=Yva[e];this.A&&g.vh(this.A.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Nh(e.element,Math.round(h.width*a.width),f);g.Dh(e.element,m,n);g.Fn(e.element,Zva);m=h.left+h.width/2;h=h.top+l/2;g.I(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Fn(e.element,Yva);g.I(e.element,d);(e=g.ee(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.vh(e,"height",f+"px")}}}}};
g.k.qI=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())V2(this,this.u.impressionUrls),(a=g.ts())&&this.u.visualElement&&g.Js(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.G[a];g.I(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.I(b,"ytp-ce-shown");V2(this,c.impressionUrls);(b=g.ts())&&g.Js(b,c.visualElement);this.player.O().A&&this.player.ra("endscreenelementshown",a)}};
g.k.rI=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.En(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.En(b,"ytp-ce-shown");this.player.O().A&&this.player.ra("endscreenelementhidden",a)}};
g.k.lO=function(a){var b=this;a.target===window&&(new g.H(function(){for(var c in b.o)g.Fn(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.k.VB=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Cn(c,"ytp-ce-element");){g.Cn(c,"subscribe-label")&&W2(this,a);if(g.Cn(c,"ytp-ce-channel-subscribe"))return;c=g.ze(c)}if(!c||g.Cn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.zv(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.qP?(W2(this,a),this.zD(),this.player.pauseVideo(),c=g.zc(T2(this,a.targetUrl)),c=g.wc(c),g.WN(c,void 0,a.Bc)):(c=this.player.getVideoData().dc,
c=(0,g.x)(this.iP,this,c,T2(this,a.targetUrl),a.Bc),c=(0,g.x)(this.zD,this,c),W2(this,a,c))}}};
g.k.iP=function(a,b,c){var d=g.$p(b);a&&d&&(d.v||d.list)?g.XT(this.player.app,d.v,c,d.list,!1,void 0):g.VN(b,c)};
g.k.Qu=function(a,b){g.Cn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.I(a.element,"ytp-ce-element-hover"):this.player.O().o?(new g.H(function(){g.I(a.element,"ytp-ce-element-hover")},200)).start():g.I(a.element,"ytp-ce-element-hover"),V2(this,b.wH),U2(this,b.id,!0))};
g.k.zv=function(a,b){g.En(a.element,"ytp-ce-element-hover");g.En(a.element,"ytp-ce-force-expand");U2(this,b.id,!1)};
g.k.zD=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var Xva=[346,426,470,506,570,640,853,1280,1920],Yva="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Zva=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var fva={XQ:"current",wS:"new"};var hva={CLOSE:"close",zS:"openUrl",qF:"subscribe"},iva={OQ:"click",CLOSE:"close",FR:"hidden",kT:"rollOut",lT:"rollOver",rT:"shown"};a3.prototype.Fc=function(){var a=jva(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
var Uva={wQ:"anchored",LE:"branding",CHANNEL:"channel",WQ:"cta",IR:"highlightText",ZR:"label",PLAYLIST:"playlist",XS:"popup",xT:"speech",qF:"subscribe",JT:"title",VIDEO:"video",ZT:"website"},Tva={LE:"branding",GQ:"card",cR:"drawer",HR:"highlight",kS:"marker",cT:"promotion",TEXT:"text",bU:"widget"};g.t(h3,g.A);g.k=h3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.Zy(a,b,{id:c});a.namespace="annotations_module";d&&this.sa.set(a,d);e&&this.oa.set(a,e);g.cN(this.context.H,[a])};
g.k.Yn=function(){this.context.u.subscribe("resize",this.So,this)};
g.k.wa=function(){return this.Pa};
g.k.Sl=function(a,b,c,d,e,f){this.context.o.na(a,"click",g.Qa(this.hq,b,c,d,e||[],f||0),this);this.context.o.na(a,"touchstart",g.Qa(function(){this.Ww=!1}),this);
this.context.o.na(a,"touchmove",g.Qa(function(){this.Ww=!0}),this)};
g.k.hq=function(a,b,c,d,e,f){if(this.Ww)return!1;f&&(f.stopPropagation(),f.preventDefault());sva(this,a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.xe(this.wa())};
g.k.So=function(){};
g.k.X=function(){this.sa.clear();this.oa.clear();g.A.prototype.X.call(this)};g.t(l3,h3);g.k=l3.prototype;g.k.isAvailable=function(){var a;if(a=!!this.A.length)(a=this.u.getRootNode())?(a=g.Oh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.So=function(){var a=this.isAvailable();g.Ph(this.wa(),a);g.J(this.context.H.getRootNode(),g.KL.IV_DRAWER_ENABLED,a);C2(this.u)};
g.k.destroy=function(){var a=g.WM(g.LM(this.u));a&&a.Ou(!1,void 0);try{this.u.getRootNode().removeChild(this.F)}catch(b){}g.Po(this.T);g.ep(this.ga);this.ea&&this.ea.dispose();this.G&&this.G.dispose();h3.prototype.destroy.call(this)};
g.k.vM=function(a){this.aa.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.k.AD=function(a){if(!g.Cn(this.u.getRootNode(),"ytp-cards-teaser-shown")){if(this.o!=a){var b=g.ts(),c=this.o?this.o.card.le:this.I;b&&c&&E2(b,[c]);this.o=a;p3(this)}if(b="none"!=this.wa().style.display)2==this.context.H.getPresentingPlayerType()?b=1==this.context.H.getAdState():(b=this.context.H.getPlayerState(),c=0==b&&0===this.context.H.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.WM(g.LM(this.u)))&&c.Ou(!0,
b));this.za.isActive()||((!this.C||!this.aa.isActive()&&this.fa)&&Cva(this,a),this.za.start(910+a.card.teaserDurationMs))}};
g.k.aP=function(a){this.C||(this.o=a,p3(this),Cva(this,a),j3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.k.SF=function(){if(this.C){b3(this.context.logger,q3(this).Wd.close);var a=g.ts();a&&this.N&&g.Os(a,this.N);k3(this)}};
g.k.fG=function(){g.J(this.F,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.OH=function(){var a=g.ts(),b=q3(this);b=b?b.le:this.I;a&&b&&D2(a,[b])};
g.k.NH=function(){var a=g.ts(),b=q3(this);b=b?b.le:this.I;a&&b&&E2(a,[b])};
g.k.RH=function(){var a=q3(this);b3(this.context.logger,a.Wd.ND);var b=g.ts();b&&a&&D2(b,[a.nf,a.le])};
g.k.QH=function(){var a=g.ts(),b=q3(this);a&&b&&E2(a,[b.nf])};
g.k.PH=function(a){var b=q3(this),c=g.ts();this.o?a?(a=this.context.logger,b3(a,b.Wd.Rr),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.nf&&g.Os(c,b.nf)):(a=this.context.logger,b3(a,b.Wd.Rr),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.le&&g.Os(c,b.le)):(a=this.context.logger,b3(a,b.Wd.Rr),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.I&&g.Os(c,this.I))};g.t(r3,h3);r3.prototype.Yn=function(){h3.prototype.Yn.call(this);Dva(this)};
r3.prototype.show=function(){h3.prototype.show.call(this);var a=g.ts(),b=this.annotation.data;a&&b&&(b=b.session_data)&&D2(a,[g.ms(b.itct)])};
r3.prototype.hide=function(){h3.prototype.hide.call(this);var a=g.ts(),b=this.annotation.data;a&&b&&(b=b.session_data)&&E2(a,[g.ms(b.itct)])};g.t(s3,r3);g.k=s3.prototype;g.k.jP=function(a,b,c,d){this.A.stop();if(!this.B){var e=g.Oh(a);this.o||(g.Mh(a,e.width),g.Mh(b,e.width));g.vh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.vh(c,"right","1px");this.B=!0;g.Ph(a,!0);this.C=new g.H(function(){g.I(this.wa(),"iv-branding-active")},0,this);
this.C.start()}};
g.k.vH=function(a,b){g.En(this.wa(),"iv-branding-active");this.F=new g.H((0,g.x)(function(){g.Ph(a,!1);this.o||g.Mh(b,0)},this),250);
this.F.start();this.B=!1};
g.k.show=function(){if(!this.isActive){r3.prototype.show.call(this);if(!this.G){g.I(this.wa(),"iv-branding");var a=this.annotation.data;this.u=g.re("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Ph(this.u,!1);var b=g.re("DIV","branding-img-container",this.u);this.wa().appendChild(b);(b=this.annotation.Fc())&&this.Sl(this.u,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.re("DIV","iv-branding-context-name");
g.Be(c,a.channel_name);var d=g.re("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.o=new g.XO(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.H),this.o.ca(d);b=g.re("DIV","iv-branding-context-subscribe-caret");c=g.re("DIV","branding-context-container-inner",b,c,d);g.Ph(c,!1);d=g.re("DIV","branding-context-container-outer",c);g.vh(d,"right",
a.image_width+"px");this.wa().appendChild(d);this.A=new g.H(g.Qa(this.vH,c,d),500,this);g.C(this,this.A);this.context.o.na(this.wa(),"mouseover",(0,g.x)(this.jP,this,c,d,b,a.image_height));this.context.o.na(this.wa(),"mouseout",(0,g.x)(this.A.start,this.A,void 0))}this.G=!0}g.Ph(this.wa(),!0);this.isActive=!0;if(this.u){a=this.u;var e=void 0===e?0:e;b=g.Hh(a);c=g.Oh(a);b=(new g.sh(b.x,b.y,c.width,c.height)).width;g.Dh(a,b);e=new K2(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,Mua);g.C(this,e);this.context.A.na(e,
"begin",g.Qa(g.Ph,a,!0));e.play()}}};
g.k.hide=function(){this.isActive&&(r3.prototype.hide.call(this),g.Ph(this.wa(),!1),this.isActive=!1)};
g.k.destroy=function(){this.o&&(this.o.dispose(),this.o=null);r3.prototype.destroy.call(this)};g.t(t3,r3);g.k=t3.prototype;g.k.show=function(){this.isActive||(r3.prototype.show.call(this),this.N||(Eva(this),this.N=!0),g.Ph(this.wa(),!0),g.Xf(function(){g.En(this.wa(),"iv-promo-inactive")},100,this),this.wa().removeAttribute("aria-hidden"),this.isActive=!0,u3(this),Gva(this),Hva(this,this.G))};
g.k.hide=function(){this.isActive&&(g.I(this.wa(),"iv-promo-inactive"),this.isActive=!1,this.wa().setAttribute("aria-hidden",!0))};
g.k.hq=function(a,b,c,d,e,f){return this.C?!1:r3.prototype.hq.call(this,a,b,c,d,e,f)};
g.k.iu=function(a,b){b.stopPropagation();Gva(this);Hva(this,a);this.o.focus()};
g.k.ZG=function(a){this.M=!0;this.iu(500,a)};
g.k.YG=function(){this.M=!1;Fva(this)};
g.k.QG=function(a){a.stopPropagation();this.hide()};
g.k.SG=function(a){a.stopPropagation();u3(this);this.C=!0;g.I(this.wa(),"iv-promo-collapsed-no-delay");this.F.start()};
g.k.destroy=function(){this.F.dispose();r3.prototype.destroy.call(this)};g.t(v3,g.uN);g.k=v3.prototype;g.k.gd=function(a,b){if(!Kva(this.player.O().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.A1(b);c&&w3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(xva(this.o,b),C2(this.player)),!0}return null};
g.k.getOptions=function(){return Kva(this.player.O().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.gr=function(){if(this.B){var a=g.QM(this.player).getVideoContentRect(!0);g.Nh(this.B.element,a.width,a.height);g.Dh(this.B.element,a.left,a.top)}if(this.o){var b=this.player.fl();a=this.o;b=b.width;g.J(a.F,"iv-drawer-small",426>=b);g.J(a.F,"iv-drawer-big",1280<=b)}};
g.k.oI=function(a){Lva(this,a.state);g.T(a.state,2)&&(this.on()&&this.DA()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Ou(!1))};
g.k.load=function(){g.uN.prototype.load.call(this);Lva(this,g.SL(this.player));this.M++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.ML,this,b,this.M),d=(0,g.x)(function(){this.F=null},this);
g.tp()&&(c=Pva(this,c));c={format:"XML",zd:c,onError:d,Te:{}};a.isPharma&&(c.Te.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.O().M.get(b))&&Qva(c,b);b=b&&(b.Yo||b.Xo);if(!a.Lo||b)a.We?Mva(this,a.We,c):(this.A=(0,g.x)(this.pI,this,c),this.player.addEventListener("videodatachange",this.A));g.gN(this.player,this.B.element,4);this.gr();(b=g.NB(a))&&Vva(this,b);(b=g.OB(a))&&b.featuredChannel&&Wva(this,b.featuredChannel,b.annotationId||"branding",a.videoId||null,a.eventId||null)};
g.k.pI=function(a){var b=this.player.getVideoData();b.We&&(this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null),Mva(this,b.We,a))};
g.k.unload=function(){g.XP(this.player.app,"annotations_module",void 0);g.yb(this.G,function(a){a.destroy()});
this.I=null;this.o&&(this.o.destroy(),this.o=null,C2(this.player));this.N=!1;this.F&&(this.F.abort(),this.F=null);this.G={};this.u.hide();g.uN.prototype.unload.call(this);this.B.detach();this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null)};
g.k.ML=function(a,b,c){this.F=null;!Ova(this,b,a)&&(a=g.lq(c)&&c.responseXML?c.responseXML:null)&&(w3(this,a),g.I(this.player.getRootNode(),"iv-module-loaded"))};
g.k.DC=function(a){a==this.player.getVideoData().videoId&&(this.loaded?Rva(this):this.load())};
g.k.on=function(){return!!this.o&&this.o.isAvailable()};
g.k.DA=function(){this.on();return!!this.o&&this.o.C};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.on();this.o&&(a?c?j3(this.o,c,b):j3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):k3(this.o))};
g.k.Ou=function(a,b){this.player.S(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.X=function(){this.player.O().M.unsubscribe("vast_info_card_add",this.DC,this);g.En(this.player.getRootNode(),g.KL.IV_DRAWER_OPEN);for(var a=this.R,b=0,c=a.length;b<c;b++)g.up(a[b]);this.R.length=0;g.uN.prototype.X.call(this)};g.FN.annotations_module=v3;g.FN.creatorendscreen=P2;})(_yt_player);
