WindowManager:
    HomePage:
    SideBarPage:
    AboutUsPage:
    QuitAppPage:
    SendDataPage:
    SeeDataPage:
    

<HomePage>:
    name: "home"
    Button:
        pos_hint: {"x": 0.05, "top": 0.97}
        size_hint: 0.2, 0.05
        text: "Options"
        on_release:
            app.root.current = "sidebar"
            root.manager.transition.direction = "left"
    Button:
        pos_hint: {"center_x":0.5, "center_y": 0.8 }
        size_hint: 0.7, 0.2
        text: "CoronaCatcher (Click to check mac)"
        on_release:
            root.calculateMac()
    Label:
        pos_hint: {"center_x": 0.5, "center_y": 0.6}
        size_hint: 0.7, 0.1
        text: root.actualMac
    Label:
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        size_hint: 0.7, 0.1
        text: "PlaceHolder for YOUR NETWORK"
        

<SideBarPage>:
    name: "sidebar"
    GridLayout:
        cols: 1
        
        Button:
            text: "Home"
            on_release:
                app.root.current = "home"
                root.manager.transition.direction = "right"
        
        Button:
            text: "About Us"
            on_release:
                app.root.current = "aboutus"
                root.manager.transition.direction = "left"
                
        Button:
            text: "My MAC Addresses"
            on_release:
                app.root.current = "seedata"
                root.manager.transition.direction = "left"
                
        Button:
            text: "Delete Data & Quit"
            on_release:
                app.root.current = "quitapp"
                root.manager.transition.direction = "left"
        
        Button:
            text: "I'm Infected"
            on_release:
                app.root.current = "senddata"
                root.manager.transition.direction = "left"
                
    


<AboutUsPage>:
    name: "aboutus"
    
    Button:
        pos_hint: {"x": 0.05, "top": 0.97}
        size_hint: 0.2, 0.05
        text: "Options"
        on_release:
            app.root.current = "sidebar"
            root.manager.transition.direction = "right"
    Label:
        pos_hint: {"center_x": 0.5, "center_y": 0.8}
        size_hint: 0.4, 0.1
        text: "Our Team"
        
    Label:
        pos_hint: {"center_x": 0.5, "center_y": 0.7}
        size_hint: 0.4, 0.8
        text: "We are a team of cool students :/"
        outline_color : 100, 0, 0
    
            
    


<QuitAppPage>:
    name: "quitapp"
    Button:
        pos_hint: {"x": 0.05, "top": 0.97}
        size_hint: 0.2, 0.05
        text: "Options"
        on_release:
            app.root.current = "sidebar"
            root.manager.transition.direction = "right"
        
        
        
    Button:
        pos_hint: {"center_x": 0.5, "center_y": 0.7}
        size_hint: 0.7, 0.12
        text: "Delete Data"
        on_release:
            root.deleteDataButtonClicked()
        
    Button:
        pos_hint: {"center_x": 0.5, "center_y": 0.55}
        size_hint: 0.7, 0.12
        text: "Quit"
        on_release:
            root.quitButtonClicked()

<SendDataPage>:
    name: "senddata"
    Button:
        pos_hint: {"x": 0.05, "top": 0.97}
        size_hint: 0.2, 0.05
        text: "Options"
        on_release:
            app.root.current = "sidebar"
            root.manager.transition.direction = "right"
        
    Button:
        pos_hint: {"center_x": 0.5, "center_y": 0.7}
        size_hint: 0.7, 0.12
        text: "SendData"
        on_release:
            root.sendDataButtonClicked()
        

<SeeDataPage>:
    name: "seedata"
    
    Button:
        pos_hint: {"x": 0.05, "top": 0.97}
        size_hint: 0.2, 0.05
        text: "Options"
        on_release:
            app.root.current = "sidebar"
            root.manager.transition.direction = "right"
    
    Button:
        pos_hint: {"right": 0.95, "top": 0.97}
        size_hint: 0.2, 0.05
        text: "Renew"
        on_release:
            root.renewRecentTen()
                
    
            
            
        