WindowManager:
    HomePage:
    SideBarPage:
    AboutUsPage:
    QuitAppPage:
    SendDataPage
    SeeDataPage:
    

<HomePage>:
    name: "home"
    
    GridLayout:
        cols: 1
        
        GridLayout:
            cols: 2
            Label:
                text: "Password: "
            TextInput:
                id: passw
                multiline: False
        Button:
            text: "Submit"
            on_release: 
                app.root.current = "second" if passw.text == "tim" else "main"
                root.manager.transition.direction = "left"

<SideBarPage>:
    name: "sidebar"
    
    Button:
        text: "Go Back"
        on_release: 
            app.root.current = "main"
            root.manager.transition.direction = "right"
            
        